### ISSUE TITLE
Bug: Agent renames with Free Customization not persisting after closing and re-opening the game

### ISSUE THREAD

**Issue by CTristan** [CTristan/lobotomy-corporation-mods#30] opened 2023-02-10 11:40 UTC
Agent renames seem to stay for the duration of the game session, including going to the Main Menu and re-loading the save, but after closing and re-opening the game the agent reverts to their prior name. Appearance changes are still there so it just seems to be an issue with the name.

Steps to reproduce:
1. Rename an existing agent
2. Begin management to save changes
3. Exit game
4. Re-open game
5. Continue saved game

Expected result: Agent still has their new name.

Actual result: Agent has reverted to their original name.

Version: 4.0

**Comment by CTristan** [comment] 2023-02-10 12:04
Looks like it only affects agents that were randomly generated and then later customized. Agents that were created customized don't seem to be affected.

**Comment by SabinStargem** [comment] 2023-02-10 12:45
I had a duplicate of the special agent "Aran" before using the Free Re-Customization mod.  "Samus" has kept their changed name and altered appearance up to this point.  Dunno if that helps with narrowing the issue, but there ya go.

**Comment by CTristan** [comment] 2023-02-10 14:33
@SabinStargem Thanks for the confirmation! That matches up with what I'm seeing too, that custom agents like the special agents keep their name changes, but pre-generated ones don't. I only happened to notice this because I started from Day 1 for testing and decided to modify the starting agent who now shows the bug.

Luckily this should be an easy fix from what I'm seeing.

**Closed** 2023-02-10 14:42 UTC
Labels: bug
